### ISSUE TITLE
Problem with importing -> perobs

### ISSUE THREAD

**Issue by BerndSchmitt** [scrapper/postrunner#14] opened 2018-09-15 03:53 UTC
Hello,
I installed postrunner as root via gem2.1 install postrunner with no errors or warnings.
Then I tried to import already downloaded fit-data via postrunner import <path>/ACTIVITY and run into errors (perobs). What can I do to fix that or to get more information about the error?

Thanks for the software and best regards
Bernd

$ postrunner import /home/user/fun/Sport/GARMIN/ACTIVITY
/usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in` `require': cannot load such file -- perobs/Store (LoadError)
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /var/lib/gems/2.1.0/gems/perobs-4.0.0/lib/perobs.rb:29:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/postrunner-0.10.1/lib/postrunner/Main.rb:15:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/postrunner-0.10.1/lib/postrunner.rb:20:in `<top (required)>'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /var/lib/gems/2.1.0/gems/postrunner-0.10.1/bin/postrunner:4:in `<top (required)>'
	from /usr/local/bin/postrunner:23:in `load'
	from /usr/local/bin/postrunner:23:in `<main>'

~ $ gem2.1 list

*** LOCAL GEMS ***

bigdecimal (1.2.4)
bindata (2.3.0)
fit4ruby (2.0.0)
io-console (0.4.2)
json (1.8.1)
mini_portile2 (2.3.0)
minitest (4.7.5)
nokogiri (1.8.4)
perobs (4.0.0)
postrunner (0.10.1)
psych (2.0.5)
rake (10.1.0)
rdoc (4.1.0)
test-unit (2.1.5.0)
~ $

**Comment by ghost** [comment] 2019-05-13 19:42
Same issue here

**Comment by scrapper** [comment] 2019-07-09 18:50
Something is not right with the Ruby installation. For some reason it cannot find the PEROBS gem. This could be caused by missing permissions on the directories where the gems were installed.

gem environment

will tell you the location and the load paths it will use. Make sure permissions and path settings are correct. And Ruby 2.1 is no longer supported. Please use at least Ruby 2.4.

**Comment by fpfilko** [comment] 2020-07-26 16:44
I had the same issue, my problem was using
```
sudo gem install postrunner
```

and then `postrunner` without sudo. So, run `sudo postrunner`  or do the following (note that 2.7.0 is my ruby version): 
```
sudo gem uninstall postrunner perobs
gem install postrunner perobs --user-install
~/.gem/ruby/2.7.0/bin/postrunner import /media/....
```
to avoid ugly last command, just append ruby bin path into your `$PATH` in file `~/.bashrc` and then you can simply run `postrunner` without sudo:
```
PATH="$PATH:~/.gem/ruby/2.7.0/bin"
```

**Comment by scrapper** [comment] 2020-07-26 17:19
I've improved the installation description to cover the user install process as well. I've also included some debugging hints for permission problems. It will be included in the next release.

**Closed as completed by scrapper** 2020-07-26 17:19 UTC
